# Generated by Django 3.2.4 on 2023-09-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_category_city_jobs_mynews_vnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
